/*
 * Name: SoccerTeams
 * Date: May 27, 2015
 * Version: v0.1
 * Author: Mr. R. Misiak
 * Description: This program lists friends from a file.
 */
package edu.hdsb.gwss.misiak.ryan.ics3u.u7;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;
import nu.xom.Serializer;

/**
 *
 * @author 1misiakrya
 */
public class SoccerTeams extends javax.swing.JFrame {

    /**
     * Creates new form SoccerTeams
     */
    public SoccerTeams() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        teamLabel = new javax.swing.JLabel();
        teamField = new javax.swing.JTextField();
        addToTeamsButton = new javax.swing.JToggleButton();
        leagueLabel = new javax.swing.JLabel();
        leagueBox = new javax.swing.JComboBox();
        numberOfPlayersSpinner = new javax.swing.JSpinner();
        numberOfPlayersLabel = new javax.swing.JLabel();
        ticketCostLabel = new javax.swing.JLabel();
        ticketField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setText("Soccer Teams");

        teamLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teamLabel.setText("Team:");

        addToTeamsButton.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        addToTeamsButton.setText("Add To Teams");
        addToTeamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToTeamsButtonActionPerformed(evt);
            }
        });

        leagueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        leagueLabel.setText("League:");

        leagueBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Premier League", "La Liga", "Bundesliga", "MLS", "Ligue 1", "Serie A" }));
        leagueBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leagueBoxActionPerformed(evt);
            }
        });

        numberOfPlayersLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numberOfPlayersLabel.setText("Number Of Players:");

        ticketCostLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ticketCostLabel.setText("Ticket Cost ($XX.XX)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(addToTeamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ticketCostLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ticketField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numberOfPlayersLabel)
                                    .addComponent(teamLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leagueLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teamField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(leagueBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberOfPlayersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleLabel)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leagueLabel)
                    .addComponent(leagueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfPlayersLabel)
                    .addComponent(numberOfPlayersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketCostLabel)
                    .addComponent(ticketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(addToTeamsButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToTeamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToTeamsButtonActionPerformed

        //Creating the elements and sub-elements.
        Element teamName = new Element(ELEMENT_TEAM);
        teamName.appendChild(teamField.getText());
        Element league = new Element(ELEMENT_LEAGUE);
        league.appendChild("" + leagueBox.getSelectedItem());
        Element players = new Element(ELEMENT_PLAYERS);
        players.appendChild("" + numberOfPlayersSpinner.getValue());
        Element ticketCost = new Element(ELEMENT_TICKET_COST);
        ticketCost.appendChild(ticketField.getText());

        //Appending the children to the main element.
        league.appendChild(teamName);
        teamName.appendChild(players);
        teamName.appendChild(ticketCost);
        teams.appendChild(league);

        Element teamsRoot;

        boolean fileFound = false;

        // Checking to see if the element exists.
        try {
            teamsRoot = teamData.getRootElement();
            Elements team = teamsRoot.getChildElements();
            for (int i = 0; i < team.size(); i++) {
                if (team.get(i).getFirstChildElement("teams").getValue().equals("1956")) {
                    fileFound = true;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        //foundFile(teamData.getRootElement());

        if (!fileFound) {
            Element team = new Element("team");
        }

        //Writing the information to the window for the user to view.
        try {
            Serializer a = new Serializer(System.out);
            a.setIndent(4);
            a.setMaxLength(64);
            a.write(teamData);
        } catch (IOException ex) {
            System.err.println(ex);
        }

        //Writing the information to the file.
        try {
            FileWriter output = new FileWriter("team");
            BufferedWriter writer = new BufferedWriter(output);
            writer.write(teams.toXML());
            writer.close();
        } catch (IOException ex) {
            System.err.println(ex);
        }


    }//GEN-LAST:event_addToTeamsButtonActionPerformed
    public static int foundFile(Element teamsRoot) {
        
        // Checking to see if the element exists.
        int x = 0;
        try {
            Elements team = teamsRoot.getChildElements();
            for (int i = 0; i < team.size(); i++) {
                if (team.get(i).getFirstChildElement("teams").getValue().equals("1956")) {
                    x = 1;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return x;
    }
    private void leagueBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leagueBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leagueBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoccerTeams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoccerTeams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoccerTeams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoccerTeams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoccerTeams().setVisible(true);
            }
        });
    }

    static final String ELEMENT_TEAMS = "team";
    static final String ELEMENT_TEAM = "teamName";
    static final String ELEMENT_LEAGUE = "league";
    static final String ELEMENT_PLAYERS = "players";
    static final String ELEMENT_TICKET_COST = "ticketCost";

    Element teams = new Element(ELEMENT_TEAMS);
    Document teamData = new Document(teams);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addToTeamsButton;
    private javax.swing.JComboBox leagueBox;
    private javax.swing.JLabel leagueLabel;
    private javax.swing.JLabel numberOfPlayersLabel;
    private javax.swing.JSpinner numberOfPlayersSpinner;
    private javax.swing.JTextField teamField;
    private javax.swing.JLabel teamLabel;
    private javax.swing.JLabel ticketCostLabel;
    private javax.swing.JTextField ticketField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
