/*
 * Name: SoccerTeamsViewer
 * Date: May 27, 2015
 * Version: v0.1
 * Author: Mr. R. Misiak
 * Description: This program lists friends from a file.
 */
package edu.hdsb.gwss.misiak.ryan.ics3u.u7;

import java.io.File;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;

/**
 *
 * @author 1misiakrya
 */
public class SoccerTeamsViewer extends javax.swing.JFrame {

    private SoccerTeams parent;

    public SoccerTeamsViewer(SoccerTeams parent) {
        initComponents();
        this.parent = parent;
    }

    public SoccerTeamsViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taPremierLeague3 = new javax.swing.JScrollPane();
        premierLeagueArea3 = new javax.swing.JTextArea();
        importButton = new javax.swing.JButton();
        premierLeagueLabel = new javax.swing.JLabel();
        serieALabel = new javax.swing.JLabel();
        laLigaLabel = new javax.swing.JLabel();
        bundesligaLabel = new javax.swing.JLabel();
        mLSLabel = new javax.swing.JLabel();
        ligue1Label = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        taPremierLeague = new javax.swing.JScrollPane();
        laLigaArea = new javax.swing.JTextArea();
        taPremierLeague1 = new javax.swing.JScrollPane();
        serieAArea = new javax.swing.JTextArea();
        taPremierLeague2 = new javax.swing.JScrollPane();
        premierLeagueArea = new javax.swing.JTextArea();
        taPremierLeague4 = new javax.swing.JScrollPane();
        mLSArea = new javax.swing.JTextArea();
        taPremierLeague5 = new javax.swing.JScrollPane();
        ligue1Area = new javax.swing.JTextArea();
        taPremierLeague6 = new javax.swing.JScrollPane();
        bundesligaArea = new javax.swing.JTextArea();

        premierLeagueArea3.setEditable(false);
        premierLeagueArea3.setColumns(20);
        premierLeagueArea3.setRows(5);
        taPremierLeague3.setViewportView(premierLeagueArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        importButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        importButton.setText("Import List");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        premierLeagueLabel.setText("Premier League:");

        serieALabel.setText("Serie A:");

        laLigaLabel.setText("La Liga:");

        bundesligaLabel.setText("Bundesliga:");

        mLSLabel.setText("MLS:");

        ligue1Label.setText("Ligue 1:");

        returnButton.setText("Click to Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleLabel.setText("Soccer Teams Viewer");

        laLigaArea.setEditable(false);
        laLigaArea.setColumns(20);
        laLigaArea.setRows(5);
        taPremierLeague.setViewportView(laLigaArea);

        serieAArea.setEditable(false);
        serieAArea.setColumns(20);
        serieAArea.setRows(5);
        taPremierLeague1.setViewportView(serieAArea);

        premierLeagueArea.setEditable(false);
        premierLeagueArea.setColumns(20);
        premierLeagueArea.setRows(5);
        taPremierLeague2.setViewportView(premierLeagueArea);

        mLSArea.setEditable(false);
        mLSArea.setColumns(20);
        mLSArea.setRows(5);
        taPremierLeague4.setViewportView(mLSArea);

        ligue1Area.setEditable(false);
        ligue1Area.setColumns(20);
        ligue1Area.setRows(5);
        taPremierLeague5.setViewportView(ligue1Area);

        bundesligaArea.setEditable(false);
        bundesligaArea.setColumns(20);
        bundesligaArea.setRows(5);
        taPremierLeague6.setViewportView(bundesligaArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(premierLeagueLabel)
                                    .addGap(138, 138, 138))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(bundesligaLabel))
                                        .addComponent(taPremierLeague2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(serieALabel)
                            .addGap(169, 169, 169)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(laLigaLabel))
                                .addComponent(taPremierLeague, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(taPremierLeague6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(taPremierLeague1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(taPremierLeague4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(returnButton)
                                        .addComponent(taPremierLeague5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(mLSLabel)
                        .addGap(190, 190, 190)
                        .addComponent(ligue1Label)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleLabel)
                .addGap(31, 31, 31)
                .addComponent(importButton)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(premierLeagueLabel)
                    .addComponent(serieALabel)
                    .addComponent(laLigaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(taPremierLeague2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bundesligaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taPremierLeague6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taPremierLeague1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(taPremierLeague))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mLSLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ligue1Label, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(taPremierLeague4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taPremierLeague5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(returnButton)
                        .addGap(99, 99, 99)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed

        File file = new File("team.xml");

        Builder builder = new Builder();
        Document teamsDocument;
        Element teamsRoot;

        try {
            teamsDocument = builder.build(file);
            teamsRoot = teamsDocument.getRootElement();
            Elements teams = teamsRoot.getChildElements();

            for (int i = 0; i < teams.size(); i++) {
                switch (teams.get(i).getFirstChildElement("leagueName").getValue()) {
                    case "Premier League":
                        premierLeagueArea.setText(premierLeagueArea.getText() + "\n" + teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                        break;
                    case "Serie A":
                        serieAArea.setText(serieAArea.getText() + "\n" + teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                        break;
                    case "La Liga":
                        laLigaArea.setText(laLigaArea.getText() + "\n" + teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                        break;
                    case "Bundesliga":
                        bundesligaArea.setText(bundesligaArea.getText() + "\n" + teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                        break;
                    case "MLS":
                        mLSArea.setText(mLSArea.getText() + "\n" + teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                        break;
                    case "Ligue 1":
                        ligue1Area.setText(ligue1Area.getText() + "\n" + teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                        break;
                    default:
                        System.out.println("ERROR - Invalid League");
                        break;
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_importButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed

        new SoccerTeams().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoccerTeamsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoccerTeamsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoccerTeamsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoccerTeamsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoccerTeamsViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bundesligaArea;
    private javax.swing.JLabel bundesligaLabel;
    private javax.swing.JButton importButton;
    private javax.swing.JTextArea laLigaArea;
    private javax.swing.JLabel laLigaLabel;
    private javax.swing.JTextArea ligue1Area;
    private javax.swing.JLabel ligue1Label;
    private javax.swing.JTextArea mLSArea;
    private javax.swing.JLabel mLSLabel;
    private javax.swing.JTextArea premierLeagueArea;
    private javax.swing.JTextArea premierLeagueArea3;
    private javax.swing.JLabel premierLeagueLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextArea serieAArea;
    private javax.swing.JLabel serieALabel;
    private javax.swing.JScrollPane taPremierLeague;
    private javax.swing.JScrollPane taPremierLeague1;
    private javax.swing.JScrollPane taPremierLeague2;
    private javax.swing.JScrollPane taPremierLeague3;
    private javax.swing.JScrollPane taPremierLeague4;
    private javax.swing.JScrollPane taPremierLeague5;
    private javax.swing.JScrollPane taPremierLeague6;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
