/*
 * Name: SoccerTeamsViewer
 * Date: May 27, 2015
 * Version: v0.1
 * Author: Mr. R. Misiak
 * Description: This program lists friends from a file.
 */
package edu.hdsb.gwss.misiak.ryan.ics3u.u7;

import java.io.File;
import javax.swing.DefaultComboBoxModel;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;

/**
 *
 * @author 1misiakrya
 */
public class SoccerTeamsViewer extends javax.swing.JFrame {

    /**
     * Creates new form SoccerTeamsViewer
     */
    public SoccerTeamsViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mLSArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ligue1Area = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        bundesligaArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        serieAArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        laLigaArea = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        premierLeagueArea = new javax.swing.JTextArea();
        premierLeagueLabel = new javax.swing.JLabel();
        serieALabel = new javax.swing.JLabel();
        laLigaLabel = new javax.swing.JLabel();
        bundesligaLabel = new javax.swing.JLabel();
        mLSLabel = new javax.swing.JLabel();
        ligue1Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        importButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        mLSArea.setColumns(20);
        mLSArea.setRows(5);
        jScrollPane1.setViewportView(mLSArea);

        ligue1Area.setColumns(20);
        ligue1Area.setRows(5);
        jScrollPane3.setViewportView(ligue1Area);

        bundesligaArea.setColumns(20);
        bundesligaArea.setRows(5);
        jScrollPane4.setViewportView(bundesligaArea);

        serieAArea.setColumns(20);
        serieAArea.setRows(5);
        jScrollPane5.setViewportView(serieAArea);

        laLigaArea.setColumns(20);
        laLigaArea.setRows(5);
        jScrollPane6.setViewportView(laLigaArea);

        premierLeagueArea.setColumns(20);
        premierLeagueArea.setRows(5);
        jScrollPane7.setViewportView(premierLeagueArea);

        premierLeagueLabel.setText("Premier League:");

        serieALabel.setText("Serie A:");

        laLigaLabel.setText("La Liga:");

        bundesligaLabel.setText("Bundesliga:");

        mLSLabel.setText("MLS:");

        ligue1Label.setText("Ligue 1:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(269, 269, 269)
                                    .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(premierLeagueLabel)
                                            .addGap(127, 127, 127)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(serieALabel))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laLigaLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(bundesligaLabel)
                        .addGap(160, 160, 160)
                        .addComponent(mLSLabel)
                        .addGap(201, 201, 201)
                        .addComponent(ligue1Label)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(importButton)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(premierLeagueLabel)
                            .addComponent(serieALabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jScrollPane7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(laLigaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bundesligaLabel)
                    .addComponent(mLSLabel)
                    .addComponent(ligue1Label))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed

        File file = new File("team.xml");

        Builder builder = new Builder();
        Document teamsDocument;
        Element teamsRoot;

        try {
            teamsDocument = builder.build(file);
            teamsRoot = teamsDocument.getRootElement();
            Elements teams = teamsRoot.getChildElements();
            DefaultComboBoxModel model = new DefaultComboBoxModel();

            for (int i = 0; i < teams.size(); i++) {
                model.addElement(teams.get(i).getFirstChildElement("name").getValue());
            }

            for (int i = 0; i < teams.size(); i++) {
                if (teams.get(i).getFirstChildElement("league").getValue().equals("Premier League")) {
                    premierLeagueArea.setText(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                    System.out.println(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");

                } else if (teams.get(i).getFirstChildElement("league").getValue().equals("Serie A")) {
                    serieAArea.setText(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                    System.out.println(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");

                } else if (teams.get(i).getFirstChildElement("league").getValue().equals("La Liga")) {
                    laLigaArea.setText(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                    System.out.println(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");

                } else if (teams.get(i).getFirstChildElement("league").getValue().equals("Bundesliga")) {
                    bundesligaArea.setText(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                    System.out.println(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");

                } else if (teams.get(i).getFirstChildElement("league").getValue().equals("MLS")) {
                    mLSArea.setText(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                    System.out.println(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");

                } else if (teams.get(i).getFirstChildElement("league").getValue().equals("Ligue 1")) {
                    ligue1Area.setText(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");
                    System.out.println(teams.get(i).getFirstChildElement("teamName").getValue() + "\n");

                } else {
                    System.out.println("ERROR - Invalid League");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_importButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoccerTeamsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoccerTeamsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoccerTeamsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoccerTeamsViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoccerTeamsViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bundesligaArea;
    private javax.swing.JLabel bundesligaLabel;
    private javax.swing.JButton importButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea laLigaArea;
    private javax.swing.JLabel laLigaLabel;
    private javax.swing.JTextArea ligue1Area;
    private javax.swing.JLabel ligue1Label;
    private javax.swing.JTextArea mLSArea;
    private javax.swing.JLabel mLSLabel;
    private javax.swing.JTextArea premierLeagueArea;
    private javax.swing.JLabel premierLeagueLabel;
    private javax.swing.JTextArea serieAArea;
    private javax.swing.JLabel serieALabel;
    // End of variables declaration//GEN-END:variables
}
