/*
 * Name: Quiz
 * Date: June 10, 2015
 * Version: v0.1
 * Author: Mr. R. Misiak
 * Description: This program is the quiz portion of the quiz program.
 */
package edu.hdsb.gwss.misiak.ryan.ics3u.summative;

import java.io.File;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;

/**
 *
 * @author muirwa
 */
public class Quiz extends javax.swing.JFrame {

    private int score = 0;

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        toResultsButton = new javax.swing.JButton();
        questionTitleLabel = new javax.swing.JLabel();
        aLabel = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        cLabel = new javax.swing.JLabel();
        dLabel = new javax.swing.JLabel();
        aField = new javax.swing.JTextField();
        bField = new javax.swing.JTextField();
        cField = new javax.swing.JTextField();
        dField = new javax.swing.JTextField();
        userAnswerLabel = new javax.swing.JLabel();
        answerButton = new javax.swing.JToggleButton();
        questionNumberTitleLabel = new javax.swing.JLabel();
        questionNumberLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionArea = new javax.swing.JTextArea();
        correctAnswerLabel = new javax.swing.JLabel();
        correctAnswerField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        aRadioButton = new javax.swing.JRadioButton();
        bRadioButton = new javax.swing.JRadioButton();
        cRadioButton = new javax.swing.JRadioButton();
        dRadioButton = new javax.swing.JRadioButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        titleLabel.setText("Ryan's Quiz Questions");

        toResultsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        toResultsButton.setText("...to Results Page");
        toResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayQuizResults(evt);
            }
        });

        questionTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        questionTitleLabel.setText("Question:");

        aLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aLabel.setText("A)");

        bLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bLabel.setText("B)");

        cLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cLabel.setText("C)");

        dLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dLabel.setText("D)");

        aField.setEditable(false);

        bField.setEditable(false);

        cField.setEditable(false);

        dField.setEditable(false);

        userAnswerLabel.setText("Your Answer: ");

        answerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerButton.setText("Submit Answer");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        questionNumberTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        questionNumberTitleLabel.setText("Question #");

        questionNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        questionArea.setEditable(false);
        questionArea.setColumns(20);
        questionArea.setRows(5);
        jScrollPane1.setViewportView(questionArea);

        correctAnswerLabel.setText("Correct Answer: ");

        correctAnswerField.setEditable(false);

        messageLabel.setText("**message**");

        buttonGroup1.add(aRadioButton);
        aRadioButton.setText("A");

        buttonGroup1.add(bRadioButton);
        bRadioButton.setText("B");

        buttonGroup1.add(cRadioButton);
        cRadioButton.setText("C");

        buttonGroup1.add(dRadioButton);
        dRadioButton.setText("D");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(titleLabel)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aLabel)
                                .addGap(10, 10, 10)
                                .addComponent(aField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(correctAnswerField)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(correctAnswerLabel)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(messageLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(toResultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(answerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cField))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(questionNumberTitleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(questionNumberLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(questionTitleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userAnswerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dRadioButton)
                    .addComponent(cRadioButton)
                    .addComponent(bRadioButton)
                    .addComponent(aRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionNumberTitleLabel)
                    .addComponent(questionNumberLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionTitleLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLabel)
                    .addComponent(bField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cLabel)
                    .addComponent(cField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLabel)
                    .addComponent(dField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAnswerLabel)
                    .addComponent(aRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(answerButton)
                        .addComponent(correctAnswerLabel))
                    .addComponent(messageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toResultsButton)
                    .addComponent(correctAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayQuizResults(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayQuizResults

        new QuizResults(score).setVisible(true);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_displayQuizResults

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed

        File file = new File("Questions For Summative.xml");

        Builder builder = new Builder();
        Document questionsDocument;
        Element questionsRoot;
        int[] questionOrder = new int[10];

        for (int i = 0; i < questionOrder.length; i++) {
            questionOrder[i] = (int) (Math.random()*10) + 1;
        }

        try {
            questionsDocument = builder.build(file);
            questionsRoot = questionsDocument.getRootElement();
            Elements questions = questionsRoot.getChildElements();
            System.out.println(questions.size());
            for (int i = 0; i < questions.size(); i++) {

                System.out.println(questions.get(i).getFirstChildElement("question").getValue());
                System.out.println(questions.get(i).getFirstChildElement("answer1").getValue());
                System.out.println(questions.get(i).getFirstChildElement("answer2").getValue());
                System.out.println(questions.get(i).getFirstChildElement("answer3").getValue());
                System.out.println(questions.get(i).getFirstChildElement("answer4").getValue());
                System.out.println(questions.get(i).getFirstChildElement("correctAnswer").getValue());
                System.out.println();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_answerButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aField;
    private javax.swing.JLabel aLabel;
    private javax.swing.JRadioButton aRadioButton;
    private javax.swing.JToggleButton answerButton;
    private javax.swing.JTextField bField;
    private javax.swing.JLabel bLabel;
    private javax.swing.JRadioButton bRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cField;
    private javax.swing.JLabel cLabel;
    private javax.swing.JRadioButton cRadioButton;
    private javax.swing.JTextField correctAnswerField;
    private javax.swing.JLabel correctAnswerLabel;
    private javax.swing.JTextField dField;
    private javax.swing.JLabel dLabel;
    private javax.swing.JRadioButton dRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea questionArea;
    private javax.swing.JLabel questionNumberLabel;
    private javax.swing.JLabel questionNumberTitleLabel;
    private javax.swing.JLabel questionTitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton toResultsButton;
    private javax.swing.JLabel userAnswerLabel;
    // End of variables declaration//GEN-END:variables
}
