/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.misiak.ryan.ics3u.u6;

import java.util.Scanner;

/**
 *
 * @author 1misiakrya
 */
public class GolfStats extends javax.swing.JFrame {

    /**
     * Creates new form GolfStats
     */
    public GolfStats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayGolfScores = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        information = new javax.swing.JLabel();
        numberOfGolfScores = new javax.swing.JLabel();
        totalScore = new javax.swing.JLabel();
        lowestScore = new javax.swing.JLabel();
        highestScore = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayGolfScores.setText("Display Golf Scores");
        displayGolfScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        title.setForeground(new java.awt.Color(255, 51, 51));
        title.setText("Golf Score");

        information.setForeground(new java.awt.Color(102, 102, 255));
        information.setText("This program records the scores for a round of 18 golf holes.");

        numberOfGolfScores.setText("Number of Golf Scores Entered: ");

        totalScore.setText("Total:");

        lowestScore.setText("Lowest Score: ");

        highestScore.setText("Highest Score: ");

        userInput.setText("jTextField1");
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(highestScore)
                    .addComponent(lowestScore)
                    .addComponent(totalScore)
                    .addComponent(numberOfGolfScores)
                    .addComponent(information)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayGolfScores)
                        .addGap(33, 33, 33)
                        .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(title)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(information)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayGolfScores)
                    .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numberOfGolfScores)
                .addGap(28, 28, 28)
                .addComponent(totalScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowestScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highestScore)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        System.out.println("This program records the score for 18 holes of golf.");

        Scanner inputScore = new Scanner(System.in);
        int[] userScore = new int[18];
        int lowestHoleScore = userScore[1];
        int highestHoleScore = userScore[1];
        int totalHoleScore = 0;

        for (int hole = 0; hole < 18; hole++) {
            System.out.print("Please enter your score in hole " + (hole + 1) + ": ");
            userScore[hole] = inputScore.nextInt();
            if (lowestHoleScore > userScore[hole]) {
                lowestHoleScore = userScore[hole];
            }
            if (highestHoleScore < userScore[hole]){
                highestHoleScore = userScore[hole];
            }
            totalHoleScore = totalHoleScore + userScore[hole];
            highestScore.setText("Highest Score: " + highestHoleScore);
            lowestScore.setText("Lowest Score: " + lowestHoleScore);
            totalScore.setText("Total: " + totalHoleScore);
        }


    }//GEN-LAST:event_jTextField1ActionPerformed

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GolfStats.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GolfStats.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GolfStats.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GolfStats.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GolfStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayGolfScores;
    private javax.swing.JLabel highestScore;
    private javax.swing.JLabel information;
    private javax.swing.JLabel lowestScore;
    private javax.swing.JLabel numberOfGolfScores;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalScore;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
