/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.misiak.ryan.ics3u.u5;

/**
 *
 * @author RMisiak
 */
public class RockPaperScissorsGUI extends javax.swing.JFrame {

    /**
     * Creates new form RockPaperScissorsGUI
     */
    public RockPaperScissorsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("Rock");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Paper");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Scissors");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1)
                        .addGap(76, 76, 76)))
                .addComponent(jToggleButton2)
                .addGap(121, 121, 121)
                .addComponent(jToggleButton3)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3))
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        String userInput = "Rock";
        String computerChoice = "";
        String gameEnds = "";
        int wins = 0;
        int losses = 0;
        int ties = 0;

        int computerChoiceGenerator = (int) (Math.random() * 3 + 1);
        if (computerChoiceGenerator == 1) {
            computerChoice = "Rock";
        } else if (computerChoiceGenerator == 2) {
            computerChoice = "Paper";
        } else if (computerChoiceGenerator == 3) {
            computerChoice = "Scissors";
        }
        if (computerChoice.equals(userInput)) {
            gameEnds = "It's a tie!";
            ties = ties + 1;
        } else if (computerChoice.equals("Paper")) {
            gameEnds = "You lose...";
            losses = losses + 1;
        } else if (computerChoice.equals("Scissors")) {
            gameEnds = "You win!";
            wins = wins + 1;
        }
        jLabel1.setText("You threw " + userInput + " and the computer threw \n" + computerChoice + ". " + gameEnds);
        jLabel2.setText("Wins: " + wins + " Losses: " + losses + " Ties: " + ties);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

        String userInput = "Paper";
        String computerChoice = "";
        String gameEnds = "";

        int computerChoiceGenerator = (int) (Math.random() * 3 + 1);
        if (computerChoiceGenerator == 1) {
            computerChoice = "Rock";
        } else if (computerChoiceGenerator == 2) {
            computerChoice = "Paper";
        } else if (computerChoiceGenerator == 3) {
            computerChoice = "Scissors";
        }
        if (computerChoice.equals(userInput)) {
            gameEnds = "It's a tie!";
        } else if (computerChoice.equals("Rock")) {
            gameEnds = "You win!";
        } else if (computerChoice.equals("Scissors")) {
            gameEnds = "You lose...";
        }
        jLabel1.setText("You threw " + userInput + " and the computer threw " + computerChoice + ". " + gameEnds);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed

        String userInput = "Scissors";
        String computerChoice = "";
        String gameEnds = "";

        int computerChoiceGenerator = (int) (Math.random() * 3 + 1);
        if (computerChoiceGenerator == 1) {
            computerChoice = "Rock";
        } else if (computerChoiceGenerator == 2) {
            computerChoice = "Paper";
        } else if (computerChoiceGenerator == 3) {
            computerChoice = "Scissors";
        }
        if (computerChoice.equals(userInput)) {
            gameEnds = "It's a tie!!";
        } else if (computerChoice.equals("Paper")) {
            gameEnds = "You win!";
        } else if (computerChoice.equals("Rock")) {
            gameEnds = "You lose...";
        }
        jLabel1.setText("You threw " + userInput + " and the computer threw " + computerChoice + ". " + gameEnds);

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RockPaperScissorsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
